# Generated by Django 4.2.5 on 2023-09-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_surveypage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveypage',
            options={'permissions': (('can_view_menu_item', 'Can View SurveyJS Menu Item'),)},
        ),
    ]
